attributes :uuid,
           :name,
           :cpu_count,
           :cpu_speed,
           :maximum_memory,
           :system , 
           :guest_agent,
           :power_state,
           :hostname, 
           :data_center_uuid, 
           :description, 
           :host_uuid